export const BALANCE = 'BALANCE';
export const TRADE_NEW = 'OB_TRADE_NEW';
export const ORDER_BOOK_NEW_ORDER = 'OB_NEW_ORDER';
export const ORDER_BOOK_UPDATE_ORDER = 'OB_UPDATE_ORDER';
export const ORDER_BOOK_DELETE_ORDER = 'OB_DELETE_ORDER';
export const ORDER_BOOK_DELETE_ORDERS_THRU = 'OB_DELETE_ORDERS_THRU';

export const EXECUTION_REPORT_NEW = 'EXECUTION_REPORT_NEW';
export const EXECUTION_REPORT_PARTIAL = 'EXECUTION_REPORT_PARTIAL';
export const EXECUTION_REPORT_EXECUTION = 'EXECUTION_REPORT_EXECUTION';
export const EXECUTION_REPORT_CANCELED = 'EXECUTION_REPORT_CANCELED';
export const EXECUTION_REPORT_REJECTED = 'EXECUTION_REPORT_REJECTED';
