export const HEARTBEAT = 'HEARTBEAT';

export const SECURITY_LIST = 'SECURITY_LIST';
export const SECURITY_STATUS_SUBSCRIBE = 'SECURITY_STATUS_SUBSCRIBE';

export const MD_TRADES = 'MD_TRADES';
export const MD_TRADES_UNSUBSCRIBE = 'MD_TRADES_UNSUBSCRIBE';
export const MD_INCREMENT = 'MD_INCREMENT';
export const MD_FULL_REFRESH = 'MD_FULL_REFRESH';
export const MD_UNSUBSCRIBE = 'MD_UNSUBSCRIBE';
export const MD_OPENING = 'MD_OPENING';

export const OB_NEW_ORDER = 'OB_NEW_ORDER';
export const OB_UPDATE_ORDER = 'OB_UPDATE_ORDER';
export const OB_DELETE_ORDER = 'OB_DELETE_ORDER';
export const OB_DELETE_ORDERS_THRU = 'OB_DELETE_ORDERS_THRU';

export const EXECUTION_REPORT = 'EXECUTION_REPORT';
export const EXECUTION_REPORT_NEW = 'EXECUTION_REPORT_NEW';
export const EXECUTION_REPORT_PARTIAL = 'EXECUTION_REPORT_PARTIAL';
export const EXECUTION_REPORT_EXECUTION = 'EXECUTION_REPORT_EXECUTION';
export const EXECUTION_REPORT_CANCELED = 'EXECUTION_REPORT_CANCELED';
export const EXECUTION_REPORT_REJECTED = 'EXECUTION_REPORT_REJECTED';

export const ORDER_HISTORY = 'ORDER_HISTORY';

export const ORDER_SEND = 'ORDER_SEND';
export const ORDER_CANCEL = 'ORDER_CANCEL';

export const TRADE_HISTORY = 'TRADE_HISTORY';

export const TRADES = 'TRADES';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const BALANCE = 'BALANCE';

export const WITHDRAW_LIST = 'WITHDRAW_LIST';
export const WITHDRAW_CANCEL = 'WITHDRAW_CANCEL';
export const WITHDRAW_REFRESH = 'WITHDRAW_REFRESH';
export const WITHDRAW_PROCESS = 'WITHDRAW_PROCESS';
export const WITHDRAW_CONFIRM = 'WITHDRAW_CONFIRM';
export const WITHDRAW_REQUEST = 'WITHDRAW_REQUEST';

export const DEPOSIT_LIST = 'DEPOSIT_LIST';
export const DEPOSIT_REFRESH = 'DEPOSIT_REFRESH';
export const DEPOSIT_PROCESS = 'DEPOSIT_PROCESS';
export const DEPOSIT_REQUEST = 'DEPOSIT_REQUEST';
export const DEPOSIT_METHODS = 'DEPOSIT_METHODS';

export const LEDGER_LIST = 'LEDGER_LIST';
