export const BALANCE = 'BALANCE';
export const TRADE_NEW = 'OB_TRADE_NEW';
export const ORDER_BOOK_NEW_ORDER = 'OB_NEW_ORDER';
export const ORDER_BOOK_UPDATE_ORDER = 'OB_UPDATE_ORDER';
export const ORDER_BOOK_DELETE_ORDER = 'OB_DELETE_ORDER';
export const ORDER_BOOK_DELETE_ORDERS_THRU = 'OB_DELETE_ORDERS_THRU';

export const EXECUTION_REPORT_NEW = 'EXECUTION_REPORT_NEW';
export const EXECUTION_REPORT_PARTIAL = 'EXECUTION_REPORT_PARTIAL';
export const EXECUTION_REPORT_EXECUTION = 'EXECUTION_REPORT_EXECUTION';
export const EXECUTION_REPORT_CANCELED = 'EXECUTION_REPORT_CANCELED';
export const EXECUTION_REPORT_REJECTED = 'EXECUTION_REPORT_REJECTED';

/* eslint-disable quote-props */
export const EVENTS = {
  ORDERBOOK: {
    '0': ORDER_BOOK_NEW_ORDER,
    '1': ORDER_BOOK_UPDATE_ORDER,
    '2': ORDER_BOOK_DELETE_ORDER,
    '3': ORDER_BOOK_DELETE_ORDERS_THRU,
  },
  TRADES: {
    '0': TRADE_NEW,
  },
  EXECUTION_REPORT: {
    '0': EXECUTION_REPORT_NEW,
    '1': EXECUTION_REPORT_PARTIAL,
    '2': EXECUTION_REPORT_EXECUTION,
    '4': EXECUTION_REPORT_CANCELED,
    '8': EXECUTION_REPORT_REJECTED,
  },
};
