export default {
  HEARTBEAT: '1',
  LOGIN: 'BE',
  LOGOUT: 'BE',
  CHANGE_PASSWORD: 'BE',

  MARKET_DATA_FULL_REFRESH: 'V',
  MARKET_DATA_UNSUBSCRIBE: 'V',

  ORDER_SEND: 'D',
  ORDER_CANCEL: 'F',

  SECURITY_LIST: 'x',
  SECURITY_STATUS: 'e',
  BALANCE: 'U2',
  ORDER_LIST: 'U4',
  BROKER_LIST: 'U28',
  TRADE_HISTORY: 'U32',
  PROFILE_UPDATE: 'U38',
  API_KEY_LIST: 'U50',
  API_KEY_CREATE: 'U52',
  API_KEY_REVOKE: 'U54',
};
